import type { NextPage } from 'next';
import Head from 'next/head';
import CssNotification from '../components/utility-first/css-notification';
import TailwindNotification from '../components/utility-first/tailwind-css-notification';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        Button
      </button> */}
      <TailwindNotification />
    </>
  );
};

export default Home;
